FROM node:16-alpine as builder
WORKDIR /app
RUN npm install -g pnpm
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN pnpm build

FROM node:16-alpine
WORKDIR /app
RUN npm install -g pnpm
COPY package.json ./
COPY pnpm-lock.yaml ./
RUN pnpm install --prod
COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/main.js" ]